version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: goodFirst
      MYSQL_DATABASE: goodFirstHubDB
      MYSQL_USER: goodFirst
      MYSQL_PASSWORD: goodFirst
    ports:
      - "3308:3306"
    volumes:
      - C:/db/mysql:/var/lib/mysql
