version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: goodFirst
      MYSQL_DATABASE: goodFirstHubDB
      MYSQL_USER: goodFirst
      MYSQL_PASSWORD: goodFirst
    ports:
      - "3308:3306"
    volumes:
      - C:/db/mysql:/var/lib/mysql


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: good_first_hub_elasticsearch
    environment:
      - discovery.type=single-node         # 단일 노드 클러스터로 실행 (개발 환경에 적합)
      - bootstrap.memory_lock=true         # 메모리 락을 활성화하여 성능 향상을 도모
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"     # ES에 할당할 최소/최대 JVM 메모리 설정
      - xpack.security.enabled=false       # 보안 기능을 비활성화 (개발 환경용)
    ulimits:
      memlock:
        soft: -1                           # 메모리 락에 대한 소프트 리밋 무제한
        hard: -1                           # 메모리 락에 대한 하드 리밋 무제한
    ports:
      - "9201:9200"                        # 호스트와 컨테이너 간 9200 포트 매핑 (ES REST API 포트)
    volumes:
      - type: bind
        source: ${DB_DRIVE}:/good_first_hub/elasticsearch/data
        target: /usr/share/elasticsearch/data # 데이터를 지속적으로 저장하기 위한 볼륨
    command: >
      sh -c "if ! bin/elasticsearch-plugin list | grep -q analysis-nori; then
             bin/elasticsearch-plugin install --batch analysis-nori;
           fi && exec bin/elasticsearch"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    container_name: good_first_hub_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Elasticsearch 클러스터의 주소 지정 (서비스 이름 사용)
      - xpack.security.enabled=false                 # Kibana에서도 보안 기능을 비활성화 (개발 환경용)
    ports:
      - "5602:5601"                        # 호스트와 컨테이너 간 5601 포트 매핑 (Kibana 대시보드 포트)
    depends_on:
      - elasticsearch                      # Kibana는 Elasticsearch가 먼저 실행되어야 함
